<style>
    /*th, td {*/
    /*    padding: 8px;*/
    /*    text-align: left;*/
    /*    border-bottom: 1px solid #ddd;*/
    /*    width: 100%;*/
    /*}*/
    img {
        width: 30px;
        height: 30px;
        border-radius: 30%;
        object-fit: cover;
    }
</style>
<section class="s-pt-100 s-pb-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <div class="section-top">
                    <h2 class="section-title">Transactions</h2>
                </div>
            </div>
        </div>

        <table id="transactions" style="width: 100%" class="table  table-responsive table-striped text-light">
            <thead>
            <tr>
                <th>Profile Picture</th>
                <th>User</th>
                <th>Transaction</th>
                <th>Amount</th>
            </tr>
            </thead>
            <tbody>
            <!-- Table rows will be generated by the jQuery code -->
            </tbody>
        </table>
    </div>
</section>
